### ISSUE TITLE
Integrate an error tracking system

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#1153]
- [ ] Self-host vs sentry.io (pricing?)
- [ ] enable source map
- [ ] dashboard
- [ ] error reporting (bots, emails etc)
