### ISSUE TITLE
AFFiNE Refactor Roadmap

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1197]
**Expected Landing Date: March 1, 2023**

Derived from #1112 

# Introduction 

The major of code refactor to fit React & Next.js best practice, also fully use `BlockSuite` editor. And simplify the code structure, improve the test case.

The goal of next version of AFFiNE:

- smoothly switching workspace & page.
- minimum page refresh required
- states correction between components. (for example you intive a member, the member list should also be changed)
- bug regression reducement.  test coverage improvement, including e2e, unit test and UI test.
  - `vitest` for unit test
  - `playwright` for e2e
  - `storybook` for UI test
- plugin support for futuring UI.

## Preview

https://affine-next.vercel.app

⚠️⚠️⚠️ **This is only for development preview. It will be unstable.** ⚠️⚠️⚠️
⚠️⚠️⚠️ **The refactor is under heavy development. Some pages and functions might be unusable** ⚠️⚠️⚠️

**Local Storage and Google login has been disabled**, each page refresh will start from the first begining

## Pull Request

- [ ] https://github.com/toeverything/AFFiNE/pull/1176

### UI & Logic

- [x] WorkspaceList
- [x] WorkspaceDetail
- [x] WorkspaceSetting
  - [x] InvitePeople
  - [x] Delete Workspace
- [x] WorkspaceTrash
- [x] WorkspaceFavourite
- [x] Theme
- [x] i18n Switch

### Bug Fixes

- [ ] https://github.com/toeverything/AFFiNE/issues/1201
- [ ] https://github.com/toeverything/AFFiNE/issues/1208
- [ ] https://github.com/toeverything/AFFiNE/issues/1200
- [ ] https://github.com/toeverything/AFFiNE/issues/1199
- [x] https://github.com/toeverything/AFFiNE/issues/1198
- [ ] https://github.com/toeverything/AFFiNE/issues/1181
- [ ] https://github.com/toeverything/AFFiNE/issues/1175
- [x] https://github.com/toeverything/AFFiNE/issues/1112
- [x] https://github.com/toeverything/AFFiNE/issues/1156
- [ ] https://github.com/toeverything/AFFiNE/issues/1134

---
# Spec

## Data Center

The data center will be simplified with only two properties: a `workspaces` list and a `callback` set.

## Workspace Plugin

Each type of workspace will have its own UI components, which means that `local` and `affine` could have different UI behavior. Also this is for the futuring workspace type, like `self-hosted,` `tauri-local.`

```ts
export interface UIPlugin<Flavour extends RemWorkspaceFlavour> {
  flavour: Flavour;
  PageDetail: React.FC<PageDetailProps<Flavour>>;
  PageList: React.FC<PageListProps<Flavour>>;
  Setting: React.FC<SettingProps<Flavour>>;
  ...
}
export const UIPlugins = {
  [RemWorkspaceFlavour.AFFINE]: AffineUIPlugin,
  [RemWorkspaceFlavour.LOCAL]: LocalUIPlugin,
} satisfies {
  [Key in RemWorkspaceFlavour]: UIPlugin<Key>;
};
```

## Store

We use `jotai` instead of `zustand` now because I want to make global states less; instead of using a global object, we split the states into different part and which will make test easily.

### Redux Devtools

![image](https://user-images.githubusercontent.com/14026360/221324030-0a224e18-e03e-4cb1-b8bd-d22e257a58b7.png)

### Debug Flags

The will have many build flags so that some feature won't appear in the app, for example. You want to disable indexeddb during debugging, you need to set `enableIndexedDBProvider=false.`

### Test

We use vitest on react hooks to ensure it will work as expected. And also for the logic part of the components. Instead of the old code sturecture everything is on e2e test, which will make debug much harder.

![image](https://user-images.githubusercontent.com/14026360/221262772-9ffcb970-bc28-4c97-970b-deed487e55af.png)

```ts
describe('useLastOpenedWorkspace', () => {
  test('basic', async () => {
    const workspaceHelperHook = renderHook(() => useWorkspacesHelper());
    workspaceHelperHook.result.current.createRemLocalWorkspace('test');
    const workspacesHook = renderHook(() => useWorkspaces());
    const currentWorkspaceHook = renderHook(() => useCurrentWorkspace());
    currentWorkspaceHook.result.current[1](workspacesHook.result.current[0].id);
    const lastOpenedWorkspace = renderHook(() => useLastOpenedWorkspace());
    expect(lastOpenedWorkspace.result.current[0]).toBe(null);
    const lastOpenedWorkspace2 = renderHook(() => useLastOpenedWorkspace());
    expect(lastOpenedWorkspace2.result.current[0]).toBe(
      workspacesHook.result.current[0].id
    );
  });
});
```

**Comment by himself65** [comment]
## Some incompatible with BlockSuite

- Timing between `Workspace.getPage` and `Workspace.meta.getPageMeta` is different. `page` will later than `pageMeta`
- Workspace doesn't have a unique ID for the whole lifecycle. Currently we assume `workspace.room` is uuid
- ...

/cc @doodlewind

**Comment by doodlewind** [comment]
Regarding workspace id, It looks good to me replacing `workspace.room` with `workspace.id`, just not sure if this id should be better passed in from outside, or be generated within the `new Workspace` constructor?
