### ISSUE TITLE
AFFiNE Iteration Update Week 14

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1800]
Release: https://github.com/toeverything/AFFiNE/releases/tag/v0.0.2-2023.04.08-alpha-kreta-ayer

# Features

- [ ] ~~Single Page Sharing (#1805)~~
- [x] Page Tree (#1786)
- [ ] ~~Desktop~~
- [x] Sort workspace card by drag and drop (#1837)

## Single Page Sharing

You can share a single page instead of the whole workspace with the public.

## Page Tree

Sub-page structure support for workspace.

## Sort workspace

You can now sort the workspace by dragging and dropping in the list modal

## Desktop

- [ ] ~~#1822~~

# UI/UX Improvements

- #1797
- #1785
- #1783
- #1819
- #1837

### Reduce CSS in JS runtime (#1817)

Now we are going to use `@vanilla-extract/css` as the main stylesheet creator instead of `emotion.` This is the first step of we fully supporting SSR.

# DX Improvements

## Storybook

- [x] move workspace card to storybook (#1804)
- [x] improve storybook introduction (#1804)

# Bug Fixes

- #1827
