### ISSUE TITLE
AFFiNE 0.5 release plan

### ISSUE THREAD

**Issue by Himself65** [toeverything/AFFiNE#1852]
Previous Version: https://github.com/toeverything/AFFiNE/issues/1800

Canary.0: https://github.com/toeverything/AFFiNE/releases/tag/0.5.0-canary.0
0.5.1: https://github.com/toeverything/AFFiNE/releases/tag/0.5.1
0.5.2: https://github.com/toeverything/AFFiNE/releases/tag/v0.5.2

```[tasklist]
### Desktop
- [x] #1822
- [ ] https://github.com/toeverything/AFFiNE/pull/1896
- [ ] https://github.com/toeverything/AFFiNE/pull/1899
- [ ] https://github.com/toeverything/AFFiNE/pull/1900
- [ ] https://github.com/toeverything/AFFiNE/pull/1900
```

```[tasklist]
### Single Page Sharing
- [x] https://github.com/toeverything/AFFiNE/pull/1805
- [x] https://github.com/toeverything/AFFiNE/pull/1858
- [ ] #1880
- [ ] https://github.com/toeverything/AFFiNE/pull/1883
```
```[tasklist]
### Perf
- [x] https://github.com/toeverything/AFFiNE/issues/1869
```
```[tasklist]
### UI/UX
- [x] #1867
- [ ] https://github.com/toeverything/AFFiNE/pull/1889
- [ ] https://github.com/toeverything/AFFiNE/pull/1887
```
```[tasklist]
### DX
- [ ] #1840
``` 

```[tasklist]
### Bugs
- [ ] https://github.com/toeverything/AFFiNE/pull/1892
```
