### ISSUE TITLE
Bootstrap Node.js server in AFFiNE

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/AFFiNE#1921]
## Motivation

Developing business with Node.js is faster than Rust; developing your own API can greatly reduce communication overhead.

## Frameworks and tools

- Nestjs
- GraphQL
- Prisma

## Infra
- Build and deploy Node.js codes
- Build and deploy AFFiNE all in one Docker image
- Tests without any external services

```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/AFFiNE/pull/2026
- [ ] https://github.com/toeverything/AFFiNE/pull/2014
- [ ] https://github.com/toeverything/AFFiNE/pull/2773
- [ ] #2808
```

**Comment by himself65** [comment]
Please put the code into `apps/server`
