### ISSUE TITLE
Global drag support​

### ISSUE THREAD

**Issue by QiShaoXuan** [toeverything/AFFiNE#1982]
### Description

![image](https://user-images.githubusercontent.com/22772830/232406962-2d60ec4c-37a5-45fb-9376-64c6f5b32b6c.png)
As shown in the figure, page in all list should be supported to drag to favorites or pinboard list

```[tasklist]
### Tasks
- [x] https://github.com/toeverything/AFFiNE/issues/2030
- [ ] Create a global dnd context
- [ ] https://github.com/toeverything/AFFiNE/issues/2029
- [ ] #2216
- [ ] https://github.com/toeverything/design/pull/2
```

**Comment by xell** [comment]
Because this issue is too old to reflect the new sidebar in AFFiNE 0.6, and part of it is included in a new task in 0.7, so I closed it and please refer to https://github.com/toeverything/AFFiNE/issues/2650 for latest situation.
