### ISSUE TITLE
​UI Inspection Issues for Kreta Ayer [tasklist]

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#1998]
### What happened?

```[tasklist]
### Edgeless
- [ ] https://github.com/toeverything/AFFiNE/issues/2004
- [ ] https://github.com/toeverything/AFFiNE/issues/2099
```

```[tasklist]
### Subpage and linked page
- [x] Sidebar scroll adjustment
- [x] Sidebar favourites and pinboard empty tips fonts size
- [ ] https://github.com/toeverything/AFFiNE/issues/2101
```

```[tasklist]
### Single page sharing
- [x] The height of Share button should be 32px instead of 36px. @JimmFly
```

```[tasklist]
### General
- [ ] https://github.com/toeverything/AFFiNE/issues/2009
- [x] #2092  @Himself65
- [x] Sidebar "Discover What's New" background color @JimmFly
- [x] Colors in Design System @Flrande
- [ ] https://github.com/toeverything/AFFiNE/issues/2100
```

**Comment by xell** [comment]
Close as all fixed.
