### ISSUE TITLE
Increase the length of Workspace title

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2047]
```[tasklist]
### Tasks
- [x] Increase the length of Workspace to 50 characters.
- [x] Use "..." to indicate the end of the last character for titles that exceed the display range.
- [ ] Use Hovertips to display titles that cannot be fully shown when hovering the mouse.
- [ ] Keep the title display fixed with a secure boundary on the right side of the Sidebar and dynamically adjust with the width.
```

**Comment by himself65** [comment]
The thrid the forth cannot be finished because of some issues on the sidebar. Need to be refactored

**Comment by tzhangchi** [comment]
This task has been completed up to 50%, and I am grateful for the effort put in so far. However, there has been no progress for almost two months. To stay on top of priorities, I will close this issue for now and keep an eye out for new suggestions in the future. Thank you for your contributions.
