### ISSUE TITLE
A list of self-test issues from April [tasklist]

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#2068]
# Issues List

```[tasklist]
## Problem with Latest Version
- [x] Dark mode sidebar UI not working. [Link](https://affine.pro/download)
```

```[tasklist]
## Pinboard (removed and deprecated)
- [x] Unclear why it's a page and no introduction provided.
- [x] No idea how to use the main area of a new page.
- [x] Confusion about the source of the double link.
- [x] toeverything/AFFiNE#2073
```

```[tasklist]
## Copylink
- [ ] toeverything/AFFiNE#2072
- [x] Examined link is incorrect(releated to toeverything/AFFiNE#2072 )
```

```[tasklist]
## Shared Page
- [x] toeverything/AFFiNE#2076
```

```[tasklist]
## Sidebar
- [x] Sidebar looks unattractive. It would be better if Favourite is not shown when there are no bookmarks.
- [x] Sidebar needs to be grouped.
```

```[tasklist]
## Workspace
- [x] Initializing the first Markdown in a workspace is slow.
- [x] Backlinks' bubble is not prominent enough.
```

```[tasklist]
## UI
- [x] No borders of popover component provided.
- [x] toeverything/blocksuite#2344
```

```[tasklist]
## Exporting
- [x] HTML and markdown images disappear when exported. (Releated to https://github.com/toeverything/blocksuite/issues/2228)
- [x] Unable to use fileblock. Related to https://github.com/toeverything/blocksuite/issues/2534
```

```[tasklist]
## Embedding
- [x] Unable to embed pages from finance and personnel systems as they do not support iframe blocks.
```

```[tasklist]
## Commands
- [ ] Delete function is unclear.
```

```[tasklist]
## Pinboard (removed and deprecated)
- [x] Need a Youtube tutorial on how to use Pinboard.
```

```[tasklist]
## Local-First
- [x] Sign in AFFINE Cloud before introducing the concept.
```

Note: These are worth discussing, but not necessarily all need to be addressed.
