### ISSUE TITLE
A stable local-first Electron Client

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/AFFiNE#2106]
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/AFFiNE/issues/2105
- [ ] https://github.com/toeverything/AFFiNE/issues/1945
- [ ] https://github.com/toeverything/AFFiNE/issues/1720
- [ ] https://github.com/toeverything/AFFiNE/issues/1658
- [ ] https://github.com/toeverything/AFFiNE/issues/1572
- [ ] https://github.com/toeverything/AFFiNE/issues/2189
- [ ] #2491
```
