### ISSUE TITLE
New design system color check

### ISSUE THREAD

**Issue by Svaney-ssman** [toeverything/AFFiNE#2133]
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/AFFiNE/issues/2130
- [ ] https://github.com/toeverything/AFFiNE/issues/2131
- [ ] https://github.com/toeverything/AFFiNE/issues/2129
- [ ] https://github.com/toeverything/AFFiNE/issues/2128
- [ ] https://github.com/toeverything/blocksuite/issues/2339
- [x] https://github.com/toeverything/AFFiNE/issues/2337
```

**Comment by xell** [comment]
All issues were fixed.
