### ISSUE TITLE
New all pages and sidebar

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#2153]
A new All Pages page and sidebar based on the OSS storage model of file system, that is, all pages are flatten stored with relationship to others for query.

- [ ] Sidebar: combine Favorites and Pinboard into one component. [internal link](https://toeverything.feishu.cn/wiki/wikcnjN66x3SL9aEctN56O1lAUc)
- [ ] All Pages: sort by name, creation date, updated date, etc. [internal link](https://toeverything.feishu.cn/wiki/wikcnSRjEP363hXwjLyYgHIcnoe)
- [ ] All Pages: filter by simple or complex queries.
- [ ] Global: any file (e.g. items in All Page or links in pages) should be dragged and dropped from and to anywhere.

Related issues, which might be merged or modified:

- [ ] #1384 
- [ ] #1563

**Comment by xell** [comment]
As being splited as the following issues, this issue was closed.

- #2326 
- #2327 
- #1982
