### ISSUE TITLE
The image preview function does not meet the requirements of the UI design

### ISSUE THREAD

**Issue by joebeijing** [toeverything/AFFiNE#2361]
memo:

- [x] Display image
- [x] Action bar implementation
- [x] Zooming
- [x] Image Download
- [x] Copy to clipboard
- [x] Caption display
- [x] Caption display when zooming in
- [x] Simple dragging
- [x] Delete image via action bar
- [x] Download image with the original image name (Replaced with block id)
- [x] Stop dragging at the boundary of the image
- [x] Retain dragging position
- [x] advanced caption display behavior (another style of image caption, can be referenced in figma)
- [x] Responsive breakpoint behavior under 960px

See https://github.com/toeverything/AFFiNE/pull/2720 for the progress.

Related with https://github.com/toeverything/AFFiNE/issues/1582

**Comment by danielchim** [comment]
advanced caption display behavior will not be included for alternative solution suggested.

**Comment by joebeijing** [comment]
> Stop dragging at the boundary of the image was not mentioned from UI design (only as an QOL feature), the priority will be lowered from other important UI details/feature bugs.

What is the exact meaning of "Stop dragging at the boundary of the image", thank you.

**Comment by danielchim** [comment]
> > Stop dragging at the boundary of the image was not mentioned from UI design (only as an QOL feature), the priority will be lowered from other important UI details/feature bugs.
> 
> 
> 
> What is the exact meaning of "Stop dragging at the boundary of the image", thank you. 

- In some image preview implementations the user will not able to drag further when they reached to any edge of the image. In the current implementation you can drag beyond the edge of the image.
