### ISSUE TITLE
SQLite provider should support subdocument​

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#2798]
SQLite provider will not work if blocksuite uses subdocs

Related upstream
- https://github.com/toeverything/blocksuite/pull/2948

```[tasklist]
### Tasks
- [x] support download
- [x] support syncing when first connected / add / removed pages
- [x] support persisting subdoc in .affine / .
- [x] optimize DB persisting
```

**Comment by himself65** [comment]
Any update?

**Comment by pengx17** [comment]
Should have been fixed in https://github.com/toeverything/AFFiNE/pull/2991
