### ISSUE TITLE
Workspace support for new server

### ISSUE THREAD

**Issue by darkskygit** [toeverything/AFFiNE#2802]
```[tasklist]
### Tasks
- [ ] binary get/set
- [ ] block get/set/del
- [ ] block search
- [ ] blob get/set
```
