### ISSUE TITLE
Initialize Cloud cluster and CI/CD based on helm and k8s

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/AFFiNE#2865]
```[tasklist]
### Tasks
- [x] Initialize k8s cluster and configuration
- [ ] https://github.com/toeverything/AFFiNE/pull/2860
- [ ] Build all in one Docker image
- [x] Helm charts #2870
- [x] publish helm charts #2875
- [ ] CI/CD supports branching deployment, removes Vercel usage
```
