### ISSUE TITLE
Add app shortcut keys for switching between Page and Edgeless Mode

### ISSUE THREAD

**Issue by houjoe0829** [toeverything/AFFiNE#2919]
- Mac：⌥ + S
- Win：Alt + S
- The information in the settings and shortcut key instructions needs to be updated

How do you think @xell 

And I also updated in [internal doc](https://toeverything.feishu.cn/wiki/Aop6wmBAyiVLSzkkyRXc6UT0nfd) about shortcuts
```[tasklist]
### Tasks
- [x] Add keyboard input support
- [x] Apply keybind style
- [x] Update keybind list
```

**Comment by joebeijing** [comment]
> My preference would be a combination of `⌥+S` for Mac or `Alt+S` for Win. It's a 2-key shortcut, easy for pressing, and is unique enough to be distinguished with other functions.

Got it, I revised it.

**Comment by hwangdev97** [comment]
And we need add tooltips for this shortcut:

![shot-2023-06-30-10 24 56@2x](https://github.com/toeverything/AFFiNE/assets/24713927/6e2c5405-7ec7-418c-b717-6a0ede65c1c8)

**Comment by danielchim** [comment]
I am concerned this may let users who rely on alt key for text input can't able to type specific words, maybe we need to switch to another hotkey?

**Comment by hwangdev97** [comment]
I think we can address this by offering the functionality to customize keyboard shortcuts. 

![shot-2023-07-06-14 41 48@2x](https://github.com/toeverything/AFFiNE/assets/24713927/42b57067-341c-40b4-9dc9-1e0678bf3018)

**Comment by xell** [comment]
It's done.
