### ISSUE TITLE
[feature]: Roadmap issue before beta

### ISSUE THREAD

**Issue by alt1o** [toeverything/AFFiNE#293]
We have added the following issues to the roadmap. Our roadmap will release in these days.

### Multi language
- [x] Multi language support: https://github.com/toeverything/AFFiNE/issues/242
- [x] Maybe new language support can be added: https://github.com/toeverything/AFFiNE/issues/151
- [x] Support Chinese: https://github.com/toeverything/AFFiNE/issues/327

### Support docker or self host
- [ ] Persisted data and dedicated users with OpenID Connect support: https://github.com/toeverything/AFFiNE/issues/244
- [x] Adds support for Docker: https://github.com/toeverything/AFFiNE/issues/235
- [x] How to configure docker to map data outside of docker: https://github.com/toeverything/AFFiNE/issues/209
- [x] Add arm64 Support to the Docker Images: https://github.com/toeverything/AFFiNE/issues/185

### Support table
- [x] Support basic table: https://github.com/toeverything/AFFiNE/issues/213

### Optimize build
- [x] Slow build speed: https://github.com/toeverything/AFFiNE/issues/203

### Support PWA
- [ ] Add PWA function: https://github.com/toeverything/AFFiNE/issues/257

### Support mobile or browser compatibility
- [ ] Mobile browser support: https://github.com/toeverything/AFFiNE/issues/251
- [ ] Browser compatibility issues in Chrome and Safari: https://github.com/toeverything/AFFiNE/issues/87

###  Support file export
- [ ] Support for exporting files e.g. pdf, doc: https://github.com/toeverything/AFFiNE/issues/246

###  Support mathematical formula
- [ ] Extended input support - mathematical support (Mathjax, KaTeX, server-side LaTeX renderer, Mathlive, etc. ): https://github.com/toeverything/AFFiNE/issues/170

###  Reading mode
- [ ] Content still editable in reading mode: https://github.com/toeverything/AFFiNE/issues/72

### Support Mindmap
- [ ] https://github.com/orgs/toeverything/projects/4/views/18

**Comment by HeJiachen-PM** [comment]
![20220821-013819](https://user-images.githubusercontent.com/79301703/185759580-a2f0304f-40f6-4d8d-bd47-727dd4c3f086.png)

**Comment by cosmic-flood** [comment]
Just give you un example of a tool

> ![20220821-013819](https://user-images.githubusercontent.com/79301703/185759580-a2f0304f-40f6-4d8d-bd47-727dd4c3f086.png)

Try this tool

https://featbit.feedbear.com/roadmap

**Comment by Avey777** [comment]
> Try these tools
> 
> https://featbit.feedbear.com/roadmap
> 
> Open source one: https://fider.io/

fider 怎么部署，我这边尝试部署 一直不成功 fider 会不停的重启

**Comment by cosmic-flood** [comment]
> > Try these tools
> > https://featbit.feedbear.com/roadmap
> > Open source one: https://fider.io/
> 
> fider 怎么部署，我这边尝试部署 一直不成功 fider 会不停的重启

还没有具体尝试，但是我又找到了个新方法，用的是 trello。只需要安装一个voting的插件就可以了，纯免费，且受众性强。最大的缺点是需要登录 trello，不过这样也规避了机器人投票的现象。

https://trello.com/b/3oF8zYQX/featbit-roadmap

**Comment by alexanderadam** [comment]
Does that mean that things like [https://github.com/toeverything/AFFiNE/issues/244](Persisted data and dedicated users with OpenID Connect support) should rather be a card in [Trello](https://trello.com/b/3oF8zYQX/featbit-roadmap)?
