### ISSUE TITLE
Quick Search: new design and function (cmd-k / ctrl-k ) [tasklist]

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3294]
From IDEs to GTD apps, cmd-k (ctrl-k for Windows) menu is gradually in the heart of end-user interaction with the software as it offers an integrated center for various operations. A comprehensive study could be referred to [Command K Bars](https://maggieappleton.com/command-bar). Hence in the 0.8 milestone, we'd like to introduce a brand new cmd-k menu for:

```[tasklist]
### Phase 1
- [ ] https://github.com/toeverything/AFFiNE/pull/4408
- [ ] #4477
- [ ] #4514
- [ ] #4568
- [x] Showing the found blocks in search result
- [x] Highlight searched results
- [x] Search result empty state
```

```[tasklist]
### Phase 2 backlog
- [ ] Tags management via CMD-K
- [ ] Single source of truth keybinding
- [ ] Commands for controlling Blocksuite related editor behaviors
```

```[tasklist]
### Bug tracking
- [ ] Crash on "failed to execute 'querySelector' on 'Element': '[cmdk-item=""][data-value=''] ...' is not a valid selector"
```

**Comment by houjoe0829** [comment]
Note: The priority for this implementation is to index tags, collections, and other content. Then, we will consider supporting search and execution of settings options. This does not currently include other operations within Page and Edgeless.

**Comment by Svaney-ssman** [comment]
Please [check design in Figma](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=3-3&mode=design)

**Comment by zanwei** [comment]
issues:

1. **There will be no content in the search results**(Please try to see if you can reproduce)
![image](https://github.com/toeverything/AFFiNE/assets/40333372/53507d18-0ff9-4304-ae23-417b279c23e8)


2. **When selecting content using the "up" and "down" keys on the keyboard, the mouse will disappear**

3. **Search results document title disappears**
<img width="666" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/3e0478e9-f239-4243-9193-e842bd0a9581">

cc @pengx17 @joooye34
