### ISSUE TITLE
New design for the title bar and right sidebar [tasklist]

### ISSUE THREAD

**Issue by xell** [toeverything/AFFiNE#3295]
In the previous version of AFFiNE, there's only one sidebar located in the left. In this milestone, with new AI and outline (a.k.a. table of contents), we will present a right sidebar as a top-level container to include the above and a re-designed block hub, making the app easy for advanced usages. As a result, the title bar will be improved too.

- [ ] new UI layout, including a creative arrangement and presentation of title bar, left sidebar and the new right sidebar, while keeping the elegance and minimalist appearance.
- [x] various improvements of title bar, including
    - [x] edit title https://github.com/toeverything/AFFiNE/issues/2645
    - [x] dropdown menu https://github.com/toeverything/AFFiNE/issues/3602
    - [x] title max width https://github.com/toeverything/AFFiNE/issues/3533
    - [x] height and width such as https://github.com/toeverything/AFFiNE/issues/1499
    - [x] fix bugs such as https://github.com/toeverything/AFFiNE/issues/3278 https://github.com/toeverything/AFFiNE/issues/3533
- [ ] new right sidebar
    - [ ]  AI panel
    - [ ] outline panel (table of contents) https://github.com/toeverything/AFFiNE/issues/1557 https://github.com/toeverything/blocksuite/issues/4159
    - [ ] redesign of block hub, related with https://github.com/toeverything/blocksuite/issues/2445
    - [ ] redesign of Help and Feedback button
