### ISSUE TITLE
Cloud server metrics logging and tracing

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/AFFiNE#3305]
```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/AFFiNE/pull/3160
- [ ] https://github.com/toeverything/AFFiNE/issues/3303
- [ ] https://github.com/toeverything/AFFiNE/issues/3304
- [ ] https://github.com/toeverything/AFFiNE/issues/3306
```
