### ISSUE TITLE
Electron infra refactor

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3318]
- [ ] #3430
- [ ] data flow
- [ ] multiple window manager
- [ ] https://github.com/toeverything/AFFiNE/issues/3310
- [ ] Import / Export workspace logic

**Comment by pengx17** [comment]
Can you elaborate more on "CLI" & "dataflow"?

**Comment by himself65** [comment]
> Can you elaborate more on "CLI" & "dataflow"?

We need some utilities to help our members and people to export/import workspace in the easiest way

- CLI
  - `affine --export $workspaceId /path/to/file`
  - `affine --import /path/to/newDbFile`
  - `affine --migrate /path/to/oldDbFile`
- dataflow
  - keep track of yDoc update (need discussion)
  - flaky test investigation
