### ISSUE TITLE
AFFiNE 0.8 Release plan

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3452]
Upstream: https://github.com/toeverything/AFFiNE/issues/1935

## Feature

```[tasklist]
### Cloud(closed beta)
- [x] Login
- [x] Sync with the server
- [x] Collaborative
- [x] Invite people
```

```[tasklist]
### Plugin Infra
- [x] Dev CLI
- [x] Dynamic import
```

```[tasklist]
### Copilot(beta)
- [ ] https://github.com/toeverything/AFFiNE/issues/2863
```

```[tasklist]
### Electron
- [ ] CLI
- [ ] Daily Note
```

## Improvement
- [x] New AFFiNE UI
- [x] Lazy Provider
- [x] SPA

**Comment by himself65** [comment]
Now it's feature freeze. In the following 2 weeks we will focus on bug fixing

**Comment by TABREZ-96** [comment]
I Would like to Know if your team is hiring. I have already sent an email but no respose.

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0-beta.0

**Comment by himself65** [comment]
https://github.com/toeverything/AFFiNE/releases/tag/v0.8.0
