### ISSUE TITLE
Login function details optimization

### ISSUE THREAD

**Issue by QiShaoXuan** [toeverything/AFFiNE#3556]
```[tasklist]
### Tasks
- [ ] All send email API should support expiration check
- [ ] If the e-mail link sent by Next-auth expires, we need to jump to the /expired route
- [ ] The changePassword API also needs to support the operation of forgetting the password. Therefore, a token for login authentication needs to be sent with the email
- [ ] We need to discuss the interaction after the e-mail change
- [ ] E-mail content is draft now
- [ ] Add test cases
```
