### ISSUE TITLE
Improve invitation process

### ISSUE THREAD

**Issue by QiShaoXuan** [toeverything/AFFiNE#3870]
```[tasklist]
### Tasks
- [x] Add `getInvitationInfo` API to get the inviter and invited workspace ( used for invitation email and invitation page)
- [x] Modify invitation email UI
- [x] Modify invitation page UI
- [x] Check sign in status before jump to invited workspace，if not, open sign page
- [x] Add pending status in member list
- [x] Modify member list style
- [x] Need confirm modal before remove member or leave workspace
- [x] Add sign page
- [x] Load invitee workspace before enter home page
```

**Comment by himself65** [comment]
Closing as all tasks have done
