### ISSUE TITLE
AFFiNE 0.9.0 Iterate Plan

### ISSUE THREAD

**Issue by himself65** [toeverything/AFFiNE#3958]
## Features

```[tasklist]
### Cloud / Server
- [ ] Login System enhancement
- [ ] Detailed permission control
- [ ] Offline mode
- [ ] Syncing status
```

```[tasklist]
### Pricing
- [ ] Connect with stripe
```

```[tasklist]
### Plugin System
- [ ] Download the plugin from the third-party website (currently from GitHub repo)
- [ ] Permission control
  - [ ] Network
  - [ ] Local Storage
  - [ ] UI register
- [ ] Official plugin support
```

```[tasklist]
### Core
- [ ] Smart quick search (including tags, collections, block content)
- [ ] UI components rewrite to `@toeverything/component` (by @QiShaoXuan)
```

---

## Housekeeping

- Desktop self-update
- Bug fixes
- e2e test coverage on local/cloud/plugin/desktop
- DX improvement
- code style unify

## Others

- AFFiNE Copilot update #2863

**Comment by himself65** [comment]
Related:

- https://github.com/toeverything/AFFiNE/issues/3992
- https://github.com/toeverything/AFFiNE/issues/3991
- https://github.com/toeverything/AFFiNE/issues/3990
- https://github.com/toeverything/AFFiNE/issues/3989
- https://github.com/toeverything/AFFiNE/issues/3988
- https://github.com/toeverything/AFFiNE/issues/3944
