### ISSUE TITLE
house keeping for server​​

### ISSUE THREAD

**Issue by darkskygit** [toeverything/AFFiNE#4151]
```[tasklist]
### Tasks
- [ ] extract auth guard config
- [ ] use a unified redis instance
- [ ] switch affine/native to jwst-core(y-octo version)
- [ ] extract permission check codes
- [ ] feature gate for user
```
