### ISSUE TITLE
​Payment & Subscription support

### ISSUE THREAD

**Issue by forehalo** [toeverything/AFFiNE#4439]
### Description

This issue is used to track the progress of **payment and subscription system** implementation. Basically we will use stripe for billing. Here is the tasks list that we should achieve.

```[tasklist]
### Target PR
- [ ] https://github.com/toeverything/AFFiNE/pull/4410
- [ ] All PRs should be targeting to `payment-system` branch
```

```[tasklist]
### Backend
- [x] basic stripe integration with nestjs #4440
- [ ] https://github.com/toeverything/AFFiNE/issues/4460
- [x] subscriptions CRUD #4492
- [x] invoices CRUD #4533
- [ ] https://github.com/toeverything/AFFiNE/issues/4526
- [ ] mails in subscription lifecycle
```

```[tasklist]
### Frontend
- [x] Plan settings #4599 (partially done)
- [x] User billing settings #4652 (partially done)
- [x] P0: account subscription status (setting modal, workspace popup) @JimmFly
- [x] P0: account setting - storage usage @JimmFly
- [x] P0: workspace setting - member invitation limit tips @JimmFly
- [x] P0: plans setting - plan switch period text (yearly <> monthly) @CatsJuice
- [x] P1: plans setting- scroll UX - scroll to current plan when plan switched @CatsJuice
- [x] P1: plans setting - loading skeleton @CatsJuice
- [x] P0: change subscription - confirm dialog, successful tips @CatsJuice
- [x] P0: cancel subscription - confirm dialog, successful tips @CatsJuice
- [x] P0: payment successful callback page @JimmFly
- [ ] P0: subscription status change emails stripe template (P1: AFFiNE template) @joooye34
- [ ] P0: billing setting - information loading, history loading @CatsJuice
- [x] P0: canary - account upgrade dialog
- [ ] P1: usage limit - storage sync and failed tips
- [ ] P1: usage limit - invite member and full member dialog
- [ ] P0: usage limit - file upload and dialog blocksuite bump version and server limit
- [x] P0: i18n
- [ ] P0: Site Login Payment Process (login and to stripe) @joooye34
- [x] P0: payment-plans - Signup action  @CatsJuice
- [x] P0: payment-plans - Contact sale action @CatsJuice
- [x] P0: electron - open payment page (Support by XP, no need to do extra things)
- [x] P0: settings - left menu list @JimmFly
- [ ] P0: plan setting - loading error (include offline) @CatsJuice
- [ ] P1: billing setting - pagination
- [ ] P1: billing setting - currency format
- [x] P0: billing setting - payment method open stripe customer portal @CatsJuice
```
```[tasklist]
### Testing
- [ ] payment e2e testing
- [ ] e2e story - yearly payment
- [ ] key frame - unauth plans
- [ ] key frame - strage usage
```

**Comment by Svaney-ssman** [comment]
Check [the design on Figma](https://www.figma.com/file/rfH3P9Wbz4IEp2Ai18O8dV/%E2%96%B6%EF%B8%8F-Affine.2023.Late?type=design&node-id=9460-72589&mode=design)
