### ISSUE TITLE
New Collections [tasklist]​

### ISSUE THREAD

**Issue by pengx17** [toeverything/AFFiNE#4601]
[Internal doc](https://insider.affine.pro/workspace/af3478a2-9c9c-4d16-864d-bffa1eb10eb6/IKmsDa5NXK)

```[tasklist]
### Development
- [x] [collection filters & collection manager refactor](https://github.com/toeverything/AFFiNE/pull/4530)
- [x] [reusable page list](https://github.com/toeverything/AFFiNE/pull/4561)
- [x] Integrate new collections with page list
- [x] new page list responsiveness implementation
- [ ] https://github.com/toeverything/AFFiNE/issues/2305
- [ ] https://github.com/toeverything/AFFiNE/issues/3410
```

```[tasklist]
### Related issues
- [ ] https://github.com/toeverything/AFFiNE/issues/4388
- [ ] https://github.com/toeverything/AFFiNE/issues/4190
- [ ] https://github.com/toeverything/AFFiNE/issues/3965
```

```[tasklist]
### WIP UI Issues
- [x] P1: Use radix-ui scrollarea to replace scroll-timeline in scroll related ui/ux
- [x] P0: Empty state for no results in collections
- [x] P0: Page list in collections modal should show "fav" status
- [x] P0: Make sure tests run without failing
- [x] P0: Various background color issues (help info, etc)
- [x] P2: DnD to add to collection
- [ ] P2: Chromatic storybook CI does not reflect the latest PR changes
- [x] P1: multi-select in all page list (to delete pages)
- [x] P0: Rename feature
- [x] P0: click page list item to select items in collections modal
- [ ] P2: Page list header overflow issue
- [x] P1: Show create page button on header after scroll page
- [x] P1: All page header in Electron
- [x] P0: Page scrolling will prevent header in Electron from dragging
- [x] ~~ P0: hide "include" section under collection's "rules" modal (add it back when dragging is done) ~~
```

**Comment by pengx17** [comment]
PR https://github.com/toeverything/AFFiNE/pull/4530
