### ISSUE TITLE
Sharing Page Feature v1

### ISSUE THREAD

**Issue by joooye34** [toeverything/AFFiNE#4646]
Sharing page v1 still leaves a lot of tasks to be done. This issue is used to track those task and ensure that all necessary functions are implemented.

```[tasklist]
### Tasks
- [ ] https://github.com/toeverything/AFFiNE/issues/3661
- [ ] https://github.com/toeverything/AFFiNE/issues/3287
- [ ] P1: Private link open desktop app
- [x] P0: Cannt disable public sharing
```

```[tasklist]
### Sharing Tasks
- [x] P?: Sharing Button On Local Workspace (Enable Cloud)
- [x] P?: Private Link (Anyone can open it now)
- [x] P?: Share With Edgeless Mode (ReadOnly issue??)
- [ ] P?: Expire Time
- [ ] P?: Search Engin Index
- [ ] P?: Show Create With AFFiNE
- [x] P?: Sharing Page Header and Sidebar
```

**Comment by joooye34** [comment]
Here is the [design](https://www.figma.com/file/hVxJQtEqyv5xw1AbCzc50M/%F0%9F%97%92%EF%B8%8F-AFFiNE-2023?type=design&node-id=534-15310&mode=designl)

**Comment by JimmFly** [comment]
https://github.com/toeverything/AFFiNE/pull/4856

**Comment by swissbyte** [comment]
#5532
