### ISSUE TITLE
Prevent the persisted data opening by the old version Client

### ISSUE THREAD

**Issue by Brooooooklyn** [toeverything/AFFiNE#4756]
```[tasklist]
### Tasks
- [ ] Our CRDT data should have version and specs
- [ ] The client should preserve the version information in the SQLite, and prevent the user from opening the data with the old version client.
- [ ] The sync server should reject the connection from the old version client to prevent the old version data from persisting into the Database
```
