### ISSUE TITLE
Issue list for 0.10

### ISSUE THREAD

**Issue by joooye34** [toeverything/AFFiNE#4785]
This version include following big features:
- payment system https://github.com/toeverything/AFFiNE/issues/4439
- new collections https://github.com/toeverything/AFFiNE/issues/4601
- new quick search https://github.com/toeverything/AFFiNE/issues/3294
- edgeless improvements https://github.com/toeverything/blocksuite/issues/5009

Testing SOP:
- https://whimsical.com/affine-payment-RNfCmJ1JkgDckKy9zuJx4H
- https://whimsical.com/new-collection-CYZGtDkvS6tsndgAmCYQrM
- https://whimsical.com/quick-search-ucNfiF8ezAtZS4E21o7ZL

```[tasklist]
### Issues
- [ ] https://github.com/toeverything/AFFiNE/issues/4782
- [ ] https://github.com/toeverything/AFFiNE/pull/4783
- [x] P1: paid plan selected state @CatsJuice
- [ ] https://github.com/toeverything/AFFiNE/pull/4789
- [ ] https://github.com/toeverything/AFFiNE/pull/4788
- [ ] https://github.com/toeverything/AFFiNE/pull/4787
- [ ] https://github.com/toeverything/AFFiNE/pull/4780
- [ ] https://github.com/toeverything/AFFiNE/pull/4776
- [x] P0: Confirg Dialog in Billing Setting @CatsJuice
- [x] P1: page list selection issues (esc/dbclick to exit selection, click to enable page selection, fav button not showing issue)
- [ ] https://github.com/toeverything/AFFiNE/pull/4797
- [ ] https://github.com/toeverything/AFFiNE/issues/4777
- [ ] https://github.com/toeverything/AFFiNE/issues/4759
- [x] P1: quick search category order should be (collections > page (title) > page (content) > commands) @JimmFly
- [ ] https://github.com/toeverything/AFFiNE/issues/4800
- [ ] https://github.com/toeverything/AFFiNE/issues/4388
- [x] P0: site pricing login and pay
- [ ] P2: currency follow stripe
- [ ] https://github.com/toeverything/AFFiNE/issues/4804
- [x] P0: subscription canceled status could not be paid member @CatsJuice
- [ ] https://github.com/toeverything/blocksuite/issues/5185
- [ ] https://github.com/toeverything/AFFiNE/issues/4828
- [ ] https://github.com/toeverything/blocksuite/issues/5184
- [ ] https://github.com/toeverything/blocksuite/issues/5089
- [ ] https://github.com/toeverything/blocksuite/issues/5188
- [ ] https://github.com/toeverything/blocksuite/issues/5189
- [ ] https://github.com/toeverything/AFFiNE/issues/4854
- [ ] https://github.com/toeverything/blocksuite/issues/5238
- [ ] https://github.com/toeverything/blocksuite/issues/5239
```

**Comment by hwangdev97** [comment]
We have a new logo that can be replaced to adapt to the new version

![shot-2023-10-31-15 44 55@2x](https://github.com/toeverything/AFFiNE/assets/24713927/5dcdf7dc-65aa-4970-b799-238d6696e35b)

**Comment by joooye34** [comment]
Let @pengx17 to replace it

> We have a new logo that can be replaced to adapt to the new version
> 
> ![shot-2023-10-31-15 44 55@2x](https://user-images.githubusercontent.com/24713927/279295799-5dcdf7dc-65aa-4970-b799-238d6696e35b.png)

**Comment by hwangdev97** [comment]
After I entering the selection mode, hope to click `Select all` to remove the selection. And, the copyright should change to `Clear selection` cc @houjoe0829 

![shot-2023-10-31-15 47 56](https://github.com/toeverything/AFFiNE/assets/24713927/bbd618b7-4c7f-40ce-ba56-768ef392d9ab)

**Comment by joooye34** [comment]
Paid for yearly pro, but monthly not selected. cc @CatsJuice 

![image](https://github.com/toeverything/AFFiNE/assets/9527419/56dcf5fd-1ab1-40f1-98a4-736a07a3b1f8)
![image](https://github.com/toeverything/AFFiNE/assets/9527419/0cee251f-0b4c-41c5-81d8-e33902b77269)

**Comment by houjoe0829** [comment]
Payment issue：After canceling the subscription, there is no confirmation pop-up when clicking the “Resume” button.

**Comment by hwangdev97** [comment]
In selected mode, we should :
- be able to exit by double-clicking elsewhere.
- holding down `Esc` should be able to exit.
- And When select mode, the file should not be opened directly.
![shot-2023-10-31-15 52 15](https://github.com/toeverything/AFFiNE/assets/24713927/479f3888-3db1-469c-82bf-c45c7085535e)

**Comment by houjoe0829** [comment]
Payment issue：Clicking Customer Support cannot trigger the behavior of sending an email
![CleanShot 2023-10-31 at 16 01 09@2x](https://github.com/toeverything/AFFiNE/assets/22443345/3570f84f-784d-45d9-83f3-1838a6ae67b2)

**Comment by houjoe0829** [comment]
Payment related text issue：After canceling the subscription, the word “annually” in the Description at the top of the Pricing Plans page needs to be changed to “yearly”, and it should not be capitalized.

![CleanShot 2023-10-31 at 16 57 06@2x](https://github.com/toeverything/AFFiNE/assets/22443345/bac04a9e-960c-4890-96c1-55776412ed0a)

**Comment by joooye34** [comment]
> there is no confirmation pop-up when clicking the “Resume” button.

cc @CatsJuice

**Comment by hwangdev97** [comment]
![shot-2023-10-31-16 17 25@2x](https://github.com/toeverything/AFFiNE/assets/24713927/ea768c70-38e3-4e6d-9996-1614f8d5b2af)

Input text's color is `textPrimary`. 
The behavior of this input bar is the same as cmd +K (quick search)

**Comment by houjoe0829** [comment]
Payment related text issue：
1. ”Unlimited local workspace“ change to ”Unlimited local workspace“
2. ”AFFiNE Cloud Storage nGB“ change to ”nGB of Cloud Storage“
3. “The maximum file size is nM" change to "nMB of maximum file size”

![CleanShot 2023-10-31 at 17 01 12@2x](https://github.com/toeverything/AFFiNE/assets/22443345/4c674442-be84-4e7f-baf4-e05962d3ccde)

**Comment by houjoe0829** [comment]
There is no response when trying to insert large files through dragging and dropping. In the expected behavior, there should be a prompt displayed when exceeding the file size limit.

https://github.com/toeverything/AFFiNE/assets/22443345/bbd2bfde-5b5f-40ec-9338-6e61024fd437

![image](https://github.com/toeverything/AFFiNE/assets/22443345/dc30f9c5-3c2a-4b5e-a97e-42ad07aeb755)

**Comment by joooye34** [comment]
https://github.com/toeverything/AFFiNE/assets/9527419/553cf977-8f2f-4e60-967d-f0770431fb8c

Keyboard actions in collection input will influence editor.  cc @pengx17

**Comment by fdjsxjn** [comment]
I hope to increase the search for characters in the file
The character search function in the article is really practical and can greatly increase search efficiency for users

Option 1: Combining ctrl+f (quickly locate the location of search content) with ctrl+k (quickly locate the approximate article of search content)
Option 2: After CTRL+K search, automatically jump to the specified location when clicking on the results



I think Option 2 is easier to implement because the existing mechanism can already search for specific content lines within the article. Simply center the display to achieve this

**Comment by fdjsxjn** [comment]
The latest version search will still crash

**Comment by pengx17** [comment]
> The latest version search will still crash

Can you give the steps of reproduction please?

**Comment by joooye34** [comment]
![image](https://github.com/toeverything/AFFiNE/assets/9527419/55f8b624-11c3-4691-a8e1-fa5a0617bdac)

If tag is empty, cloud not be clickable.

**Comment by joooye34** [comment]
Collection will close when I change chrome tab

https://github.com/toeverything/AFFiNE/assets/9527419/3b676522-505e-4d87-b4ad-ddecc8a97403

**Comment by houjoe0829** [comment]
We have not handled the display logic for the Billing and Pricing pages within the client when it is offline, and as a result, errors occur in the client after some time.

![CleanShot 2023-11-01 at 14 53 26@2x](https://github.com/toeverything/AFFiNE/assets/22443345/75f58f58-d758-4e0b-9c12-d664723213a1)
![CleanShot 2023-11-01 at 14 53 14@2x](https://github.com/toeverything/AFFiNE/assets/22443345/e64218f8-e719-4b7f-9bb1-4a97fcdaf690)
![CleanShot 2023-11-01 at 14 53 05@2x](https://github.com/toeverything/AFFiNE/assets/22443345/372efd89-f1b6-45e9-abbc-9571458fa03e)

**Comment by EYHN** [comment]
we should fix this
https://github.com/toeverything/AFFiNE/issues/4809

**Comment by joooye34** [comment]
The version is stable. If some issues haven't been fixed, create individual issue to fix.
