### ISSUE TITLE
Collections UI Issues

### ISSUE THREAD

**Issue by zanwei** [toeverything/AFFiNE#4804]
- [x] icon alignment & icon color @pengx17 

**Should**: Please adjust alignment of text and icon. Also please notice that icon should use `iconColor` instead of others

<img width="95" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/74c35023-8b04-49b4-9565-75029706853a">

<hr/>

- [x] Collection title @pengx17 

**Should**: Please change the title font size to `20px` instead of `24px`

<img width="273" alt="image" src="https://github.com/toeverything/AFFiNE/assets/40333372/a3da66d4-0fce-4f32-95b8-7c117e40d979">

<hr/>

- [x] Collection Input TextColor @3720

![shot-2023-11-01-16 54 41@2x](https://github.com/toeverything/AFFiNE/assets/24713927/a49920e7-e46b-4778-9f75-19818398a298)

```[tasklist]
### Tasks
```

**Comment by hwangdev97** [comment]
- [ ] please fix  star icon disappear
![shot-2023-11-01-16 56 58@2x](https://github.com/toeverything/AFFiNE/assets/24713927/779e3fa3-16df-47f4-95ac-7eb53bddfa95)

**Comment by hwangdev97** [comment]
-[ ] After selection, please do not close the **multi-select menu** immediately.
![shot-2023-11-01-16 58 42@2x](https://github.com/toeverything/AFFiNE/assets/24713927/3e74dbc3-7a5f-4e9e-a70f-f9edf781b2f6)

**Comment by hwangdev97** [comment]
![shot-2023-11-01-17 00 43@2x](https://github.com/toeverything/AFFiNE/assets/24713927/cb65ed92-b785-4521-9bdb-37884fef73f8)
Please modify the adaptability status here. If there is too much text, display it as '...'.

**Comment by joooye34** [comment]
The version is stable. If some issues haven't been fixed, create individual issue to fix.
