### ISSUE TITLE
🎄🎁 Roadmap 202212 

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#562]
We are mainly working on features for pathfinder.

* [x] Support Document Management System @QiShaoXuan 
* [x] Upgrade https://github.com/toeverything/blocksuite to **v0.3.0** @doodlewind 
* [x] Support Simple Quick Search @JimmFly 
* [x] Support New Page @QiShaoXuan 
* [x] Support Favorite Pager/Edgeless @QiShaoXuan 
* [x] Support Delete Pager/Edgeless @QiShaoXuan 
* [x] Support Trash Pager/Edgeless @QiShaoXuan 
* [x] Support divider block @JimmFly 
* [x] Support embed image block @DiamondThree 
* [x] Support inline popover menu (quick bar)  @lawvs 
* [x] Support code block @thorseraq 
* [x] Support shape block  @Himself65 
* [x] Exception Page @SaikaSakura @DiamondThree  
* [x] Support E2E Testing CI @QiShaoXuan @tzhangchi 
* [x] Support Changelog Bot CI @DiamondThree

**Comment by Fabioax7** [comment]
Support Permission and Collaboration will be a great feature. I intend to have an instance to be used by my company's team and having the permissions feature is essential.

**Comment by tzhangchi** [comment]
The new version will be deployed in http://pathfinder.affine.pro/

**Comment by darkskygit** [comment]
task final
