### ISSUE TITLE
📌 Overall Roadmap 202303

### ISSUE THREAD

**Issue by tzhangchi** [toeverything/AFFiNE#573]
Here is the overall roadmap towards our next major version after Downhills.

## Editor

P0
- [x] toeverything/AFFiNE#614 
- [ ] toeverything/AFFiNE#633 
- [x] toeverything/blocksuite#1289
- [ ] toeverything/AFFiNE#972
- [ ] #1332
- [ ] Support embed webpage (Youtube / Twitter / Figma)
- [ ] toeverything/AFFiNE/issues/1573

P1
- [ ] Support gallery block (TBD)
- [ ] Support bookmark block (web content with meta)
- [ ] Support citing documents
- [ ] Support mention(@) feature
- [ ] Add Release notification channel
- [ ] toeverything/OctoBase#216

Misc
- [ ] https://github.com/toeverything/blocksuite/issues/1296

## Client
- [ ] https://github.com/toeverything/AFFiNE/issues/1562

## To be confirmed
- [ ] Enterprise login (SSO / LDAP / OAuth...)
- [ ] toeverything/AFFiNE#1174 
- [ ] toeverything/AFFiNE#1173 
- [ ] Payment & plans
